CREATE TABLE IF NOT EXISTS filmorate_user (
                                user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_name varchar(40),
                                user_login varchar(40) NOT NULL,
                                user_email varchar(40) NOT NULL,
                                user_birthday date
);

CREATE TABLE IF NOT EXISTS film (
                      film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      film_name varchar(40) NOT NULL,
                      film_description varchar(200),
                      film_MPA_id integer,
                      release_date date,
                      film_duration int
);

CREATE TABLE IF NOT EXISTS MPA_rating (
                            rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            rating_desc varchar(20)
);

CREATE TABLE IF NOT EXISTS genre (
                       genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       genre_desc varchar(20)
);

CREATE TABLE IF NOT EXISTS film_genre (
                            genre_id bigint,
                            film_id bigint
);

CREATE TABLE IF NOT EXISTS friends (
                         user_id bigint,
                         friend_id bigint,
                         status_id integer
);

CREATE TABLE IF NOT EXISTS film_likes (
                            user_id bigint,
                            film_id bigint
);

CREATE TABLE IF NOT EXISTS friends_status (
                                status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                status_desc varchar(20)
);

ALTER TABLE film ADD FOREIGN KEY (film_MPA_id) REFERENCES MPA_rating (rating_id);

ALTER TABLE film_genre ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id);

ALTER TABLE film_genre ADD FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE friends ADD FOREIGN KEY (user_id) REFERENCES filmorate_user (user_id);

ALTER TABLE friends ADD FOREIGN KEY (friend_id) REFERENCES filmorate_user (user_id);

ALTER TABLE film_likes ADD FOREIGN KEY (user_id) REFERENCES filmorate_user (user_id);

ALTER TABLE film_likes ADD FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE friends ADD FOREIGN KEY (status_id) REFERENCES friends_status (status_id);
